# -*- coding: utf-8 -*-
"""Copy of Decision Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDNS_9inNgP-6UoKKvE4LvTC8b3djpZo
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier


from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# ------------------------------------------------------------
# STEP 3: Load the Kaggle Dataset
# ------------------------------------------------------------

file_path = "/content/drive/My Drive/Datasets/Rainfall.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

from sklearn.metrics import precision_score, recall_score

# -----------------------------------
# 1. Load the Kaggle dataset
# ------------------------------------

df = pd.read_csv(file_path)

print(df.head())


# -----------------------------------
# 2. Select Features
# -----------------------------------

# Using features from the actual rainfall dataset
X = df[["Area", "Annual", "Monsoon", "PrevYearYield"]]


# -----------------------------------
# 3. Select Target
# -----------------------------------

# Using the actual target column from your dataset
y = df["Target"]


# -----------------------------------
# 4. Handle Missing Values
# -----------------------------------

X = X.fillna(X.mean())


# -----------------------------------
# 5. Split the Data
# -----------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


# -----------------------------------
# 6. Create Decision Tree
# -----------------------------------

model = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)


# -----------------------------------
# 7. Train the Model
# -----------------------------------

model.fit(X_train, y_train)


# -----------------------------------
# 8. Make Predictions
# -----------------------------------

y_pred = model.predict(X_test)


# -----------------------------------
# 9. Accuracy
# -----------------------------------

accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)


# -----------------------------------
# 10. Confusion Matrix
# -----------------------------------

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)


# -----------------------------------
# 11. Precision
# -----------------------------------

precision = precision_score(y_test, y_pred)

print("\nPrecision:", precision)


# -----------------------------------
# 12. Recall
# -----------------------------------

recall = recall_score(y_test, y_pred)

print("\nRecall:", recall)


# -----------------------------------
# 13. Predict a New Sample
# -----------------------------------

new_sample_data = {
    'Area': [4000],
    'Annual': [2500],
    'Monsoon': [1400],
    'PrevYearYield': [1.5]
}

new_sample_df = pd.DataFrame(new_sample_data)

prediction = model.predict(new_sample_df)

if prediction[0] == 1:
    print("\nPrediction: High Yield (Target = 1)")
else:
    print("\nPrediction: Low Yield (Target = 0)")