# -*- coding: utf-8 -*-
"""Copy of Step by Step Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DN8CaUPV_9hreeEdVnnNqEvjeJaojBUC
"""

from google.colab import drive

drive.mount('/content/drive')

# ------------------------------------------------------------
# STEP 2: Import Libraries
# ------------------------------------------------------------

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# ------------------------------------------------------------
# STEP 3: Load the Kaggle Dataset
# ------------------------------------------------------------

file_path = "/content/drive/My Drive/Datasets/Earthquake.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

# ------------------------------------------------------------
# STEP 4: Look at the Dataset
# ------------------------------------------------------------

print(df.head())

print(df.columns)

# ------------------------------------------------------------
# STEP 5: Understand the Dataset
# ------------------------------------------------------------

print(df.info())

print(df.describe())

"""We want to predict:

Survived

0 = Did not survive
1 = Survived

Pclass
Age
SibSp
Parch
Fare
"""

# ------------------------------------------------------------
# STEP 6: Select Features and Target
# ------------------------------------------------------------

# 1. Clean the target column by removing commas and converting to numeric
df["Cleaned Death Toll"] = pd.to_numeric(df["Death toll"].astype(str).str.replace(",", ""), errors="coerce")

# 2. Since Logistic Regression is a classifier, let's create a binary category:
# 1 = High Death Toll (> 5,000 deaths)
# 0 = Low Death Toll (<= 5,000 deaths)
df["High Death Toll"] = (df["Cleaned Death Toll"] > 5000).astype(int)

# 3. Select features and binary target
features = [
    "Magnitude",
    "Year"
]

X = df[features]
y = df["High Death Toll"]

print("Features:")
print(X.head())

print("\nTarget (High Death Toll?):")
print(y.head())

# ------------------------------------------------------------
# STEP 7: Check for Missing Values
# ------------------------------------------------------------

print("Missing values in features:")
print(X.isnull().sum())

print("\nMissing values in target:")
print(y.isnull().sum())

# ------------------------------------------------------------
# STEP 8: Handle Missing Values
# ------------------------------------------------------------

# Make a copy of features to avoid SettingWithCopyWarning
X = X.copy()

# If there are any missing values in numerical columns, we can fill them with their mean/median
for col in X.columns:
    if X[col].isnull().any():
        X[col] = X[col].fillna(X[col].median())

print("Missing values in features after cleaning:")
print(X.isnull().sum())

# ------------------------------------------------------------
# STEP 9: Split Data into Training and Testing Sets
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training data:", len(X_train))
print("Testing data:", len(X_test))

# ------------------------------------------------------------
# STEP 10: Create Logistic Regression Model
# ------------------------------------------------------------

model = LogisticRegression(max_iter=1000)

print(model)

# ------------------------------------------------------------
# STEP 11: Train the Model
# ------------------------------------------------------------

model.fit(X_train, y_train)

print("Model training completed!")

"""fit() is where the machine learning happens.
 The model looks at
 Features + Known Answers
        ↓
   Learn patterns
        ↓
   Logistic Model
"""

# ------------------------------------------------------------
# STEP 12: Make Predictions
# ------------------------------------------------------------

y_pred = model.predict(X_test)

print("Predictions:")
print(y_pred[:20])

"""The predictions will be
0
1
0
1
1
0
... where 0 = Did not survive
1 = Survived
"""

# ------------------------------------------------------------
# STEP 13: Calculate Accuracy
# ------------------------------------------------------------

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("Accuracy percentage:", accuracy * 100, "%")

# ------------------------------------------------------------
# STEP 14: Confusion Matrix
# ------------------------------------------------------------

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

"""                 ACTUAL
              0          1

PREDICT  0   Correct    Wrong
         1   Wrong      Correct
"""

# ------------------------------------------------------------
# STEP 15: Classification Report
# ------------------------------------------------------------

print(classification_report(y_test, y_pred))

# ------------------------------------------------------------
# STEP 16: Predict Probabilities
# ------------------------------------------------------------

probabilities = model.predict_proba(X_test)

print(probabilities[:10])

# ------------------------------------------------------------
# STEP 17: Predict a New Earthquake
# ------------------------------------------------------------

# Creating a hypothetical new earthquake with Magnitude and Year
new_earthquake = pd.DataFrame({
    "Magnitude": [7.5],
    "Year": [2024]
})

prediction = model.predict(new_earthquake)

probability = model.predict_proba(new_earthquake)

print("Prediction:", prediction)

print("Probability of LOW death toll (<= 5000 deaths):",
      probability[0][0])

print("Probability of HIGH death toll (> 5000 deaths):",
      probability[0][1])

# ------------------------------------------------------------
# STEP 18: Human-Friendly Prediction
# ------------------------------------------------------------

if prediction[0] == 1:
    print("The model predicts: SURVIVED")
else:
    print("The model predicts: DID NOT SURVIVE")

# ------------------------------------------------------------
# STEP 19: Examine Model Coefficients
# ------------------------------------------------------------

coefficients = pd.DataFrame({
    "Feature": features,
    "Coefficient": model.coef_[0]
})

print(coefficients)

# Only attempt to fill missing values for 'Gender' if the column actually exists in df
if "Gender" in df.columns:
    df["Gender"] = df["Gender"].fillna("Unknown")
    print("Gender missing values handled.")
else:
    print("Column 'Gender' not found in current dataset. Skipping this step.")

# Import libraries
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score
)

# -----------------------------------
# 1. Load the Kaggle dataset
# -----------------------------------

# Updated to load the Earthquake dataset
df = pd.read_csv("/content/drive/MyDrive/Datasets/Earthquake.csv")

print(df.head())


# -----------------------------------
# 2. Select Features
# -----------------------------------

# Using Magnitude and Year for Earthquake prediction
X = df[["Magnitude", "Year"]]


# -----------------------------------
# 3. Select Target
# -----------------------------------

# Clean the target column by removing commas and converting to numeric
df["Cleaned Death Toll"] = pd.to_numeric(df["Death toll"].astype(str).str.replace(",", ""), errors="coerce")

# Create a binary target: 1 = High Death Toll (> 5,000 deaths), 0 = Low Death Toll
df["High Death Toll"] = (df["Cleaned Death Toll"] > 5000).astype(int)

y = df["High Death Toll"]


# -----------------------------------
# 4. Handle Missing Values
# -----------------------------------

X = X.copy()
X["Magnitude"] = X["Magnitude"].fillna(X["Magnitude"].mean())
X["Year"] = X["Year"].fillna(X["Year"].mean())


# -----------------------------------
# 5. Split the Data
# -----------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


# -----------------------------------
# 6. Create Decision Tree
# -----------------------------------

model = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)


# -----------------------------------
# 7. Train the Model
# -----------------------------------

model.fit(X_train, y_train)


# -----------------------------------
# 8. Make Predictions
# -----------------------------------

y_pred = model.predict(X_test)


# -----------------------------------
# 9. Accuracy
# -----------------------------------

accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)


# -----------------------------------
# 10. Confusion Matrix
# -----------------------------------

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)


# -----------------------------------
# 11. Precision
# -----------------------------------

precision = precision_score(y_test, y_pred)

print("\nPrecision:", precision)


# -----------------------------------
# 12. Recall
# -----------------------------------

recall = recall_score(y_test, y_pred)

print("\nRecall:", recall)


# -----------------------------------
# 13. Predict a New Earthquake
# -----------------------------------

new_earthquake = [[7.5, 2024]]

prediction = model.predict(new_earthquake)

if prediction[0] == 1:
    print("\nPrediction: High Death Toll (> 5,000 deaths)")
else:
    print("\nPrediction: Low Death Toll (<= 5,000 deaths)")