# -*- coding: utf-8 -*-
"""Supervised ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ebZfHPhBXBiH-Tq6_hIgITyBMrWUhlP
"""

from google.colab import drive

drive.mount('/content/drive')

# ------------------------------------------------------------
# STEP 2: Import Libraries
# ------------------------------------------------------------

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# ------------------------------------------------------------
# STEP 3: Load the Kaggle Dataset
# ------------------------------------------------------------

file_path = "/content/drive/MyDrive/Datasets/SocialNetworkAds.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

# ------------------------------------------------------------
# STEP 4: Look at the Dataset
# ------------------------------------------------------------

print(df.head())

print(df.columns)

# ------------------------------------------------------------
# STEP 5: Understand the Dataset
# ------------------------------------------------------------

print(df.info())

print(df.describe())

"""```markdown
We want to predict:

Purchased

0 = Did not purchase
1 = Purchased

Features:
* Age
* EstimatedSalary
```
"""

# ------------------------------------------------------------
# STEP 6: Select Features and Target
# ------------------------------------------------------------

# Using the features available in the SocialNetworkAds dataset
features = [
    "Age",
    "EstimatedSalary"
]

X = df[features]

y = df["Purchased"]

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

# ------------------------------------------------------------
# STEP 7: Check for Missing Values
# ------------------------------------------------------------

print(X.isnull().sum())

# ------------------------------------------------------------
# STEP 8: Handle Missing Values
# ------------------------------------------------------------

X = X.copy()

X["Age"] = X["Age"].fillna(X["Age"].median())

print("Missing values after cleaning:")
print(X.isnull().sum())

# ------------------------------------------------------------
# STEP 9: Split Data into Training and Testing Sets
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training data:", len(X_train))
print("Testing data:", len(X_test))

# ------------------------------------------------------------
# STEP 10: Create Logistic Regression Model
# ------------------------------------------------------------

model = LogisticRegression(max_iter=1000)

print(model)

# ------------------------------------------------------------
# STEP 11: Train the Model
# ------------------------------------------------------------

model.fit(X_train, y_train)

print("Model training completed!")

"""fit() is where the machine learning happens.
 The model looks at
 Features + Known Answers
        ↓
   Learn patterns
        ↓
   Logistic Model
"""

# ------------------------------------------------------------
# STEP 12: Make Predictions
# ------------------------------------------------------------

y_pred = model.predict(X_test)

print("Predictions:")
print(y_pred[:20])

"""```markdown
The predictions will be:
* 0 = Did not purchase
* 1 = Purchased
```
"""

# ------------------------------------------------------------
# STEP 13: Calculate Accuracy
# ------------------------------------------------------------

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("Accuracy percentage:", accuracy * 100, "%")

# ------------------------------------------------------------
# STEP 14: Confusion Matrix
# ------------------------------------------------------------

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

"""                 ACTUAL
              0          1

PREDICT  0   Correct    Wrong
         1   Wrong      Correct
"""

# ------------------------------------------------------------
# STEP 15: Classification Report
# ------------------------------------------------------------

print(classification_report(y_test, y_pred))

# ------------------------------------------------------------
# STEP 16: Predict Probabilities
# ------------------------------------------------------------

probabilities = model.predict_proba(X_test)

print(probabilities[:10])

# ------------------------------------------------------------
# STEP 17: Predict a New User
# ------------------------------------------------------------

# Creating a new user with the features used during training:
# Age = 25, EstimatedSalary = 50000
new_user = pd.DataFrame({
    "Age": [25],
    "EstimatedSalary": [50000]
})

prediction = model.predict(new_user)

probability = model.predict_proba(new_user)

print("Prediction:", prediction)

print("Probability of NOT purchasing:",
      probability[0][0])

print("Probability of purchasing:",
      probability[0][1])

# ------------------------------------------------------------
# STEP 18: Human-Friendly Prediction
# ------------------------------------------------------------

if prediction[0] == 1:
    print("The model predicts: PURCHASED")
else:
    print("The model predicts: DID NOT PURCHASE")

# ------------------------------------------------------------
# STEP 19: Examine Model Coefficients
# ------------------------------------------------------------

coefficients = pd.DataFrame({
    "Feature": features,
    "Coefficient": model.coef_[0]
})

print(coefficients)

"""### Feature Verification and Analysis
Let's analyze the `Gender` column to see if it should be included as a feature alongside `Age` and `EstimatedSalary`.
"""

# Show the breakdown of the Gender column in the original dataset
print("Gender counts:")
print(df['Gender'].value_counts())

# Calculate the purchase rate by Gender
purchase_rate_by_gender = df.groupby('Gender')['Purchased'].mean()
print("\nPurchase rate by Gender:")
print(purchase_rate_by_gender)
